title: "Systemischer Realismus"
theme: jekyll-theme-cayman
sass:
  style: compressed

include:
  - assets/css/style.css
# Optional: du kannst hier weitere Einstellungen erg√§nzen (permalink, plugins, description).
